Move ColorToolViewModel to shared project (#3624)
* Drop net7.0-windows due to EOL (#3597)

* ColorToolViewModel to shared project

* Stop compile error CS0436 on PR build

* Add root namespace